spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://ep-late-sea-aa5s1qni-pooler.westus3.azure.neon.tech:5432/spingapi
    username: spingapi_owner
    password: npg_LGbgT5dRNsF6

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  management:
    endpoints:
      web:
        exposure:
          include:
            - health
            - info

server:
  port: 8083
